version: '3.7'
services:
  uks-backend:
    image: uks-backend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: uks-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://uks-mysql:3306/uks?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: jacek
      SPRING_DATASOURCE_PASSWORD: FGDSK54$$
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql
    networks:
      - uks-net
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: uks-mysql
    volumes:
      - uks-mysql-data:/var/lib/mysql
    networks:
      - uks-net
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 1m
      timeout: 10s
      retries: 2

volumes:
  uks-mysql-data:

networks:
  uks-net:
    name: uks-net